apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: orders-events
  namespace: strimzi
  labels:
    strimzi.io/cluster: "my-cluster"
    app: orders-service
    environment: poc
    data-type: events
    criticality: high
  annotations:
    description: "Events for order processing including creation, updates, and status changes"
    owner: "orders-team@company.com"
    created-by: "poc-declarative-topics"
    retention-policy: "7-days"
spec:
  partitions: 12
  replicas: 3
  config:
    # Retention settings
    retention.ms: 604800000  # 7 days in milliseconds
    segment.bytes: 1073741824  # 1GB segment size
    retention.bytes: -1  # Unlimited bytes, time-based retention only

    # Cleanup policy
    cleanup.policy: "delete"  # Delete old segments
    delete.retention.ms: 86400000  # 1 day retention for deleted records

    # Performance settings
    compression.type: "producer"  # Use producer's compression setting
    max.message.bytes: 10485760  # 10MB max message size
    min.compaction.lag.ms: 0  # No minimum compaction lag

    # Replication and durability
    min.insync.replicas: 2  # Require at least 2 replicas for writes
    unclean.leader.election.enable: false  # Prevent data loss

    # Consumer settings
    min.cleanable.dirty.ratio: 0.5  # Compact when 50% of log is dirty
    index.interval.bytes: 4096  # Index every 4KB

    # Monitoring and metrics
    message.timestamp.type: "LogAppendTime"  # Use server time for timestamps
    message.timestamp.difference.max.ms: 9223372036854775807  # No limit on timestamp difference
